title: Job Salary Prediction - Przewidywanie Wynagrodzeń w branży IT
author: Malarz Dawid
execute:
  execute_notebooks: "off"
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
